@extends('arabic')

@section('head')
<style>@include('tahsin.style')</style>
@endsection

@section('content')
<div class="page">
  <table border="1">
    <tr>
      <td>اَنِئًا</td>
      <td>مَئِيْئًا</td>
      <td>الْمُؤْنِ</td>
      <td>مِنَ</td>
      <td>اَ أْ نَ</td>
      <td>اَ نِ</td>
      <td>اُ وْ اَ نْ</td>
      <td>اَ اِ اُ بَأْ</td>
    </tr>
    <tr>
      <td>بَنِبًا</td>
      <td>مَبِيْبًا</td>
      <td>الْمُبْنِ</td>
      <td>مِنَ</td>
      <td>بَبْنَ</td>
      <td>بَنِ</td>
      <td>بُوْ بَنْ</td>
      <td>بَ بِ بُ بَبْ</td>
    </tr>
    <tr>
      <td>تَنِتًا</td>
      <td>مَتِيْتًا</td>
      <td>الْمُتْنِ</td>
      <td>مِنَ</td>
      <td>تَتْنَ</td>
      <td>تَنِ</td>
      <td>تُوْتَنْ</td>
      <td>تَ تِ تُ بَتْ</td>
    </tr>
    <tr>
      <td>ثَنِثًا</td>
      <td>مَثِيْثًا</td>
      <td>الْمُثْنِ</td>
      <td>مِنَ</td>
      <td>ثَثْنَ</td>
      <td>ثَنِ</td>
      <td>ثُوْثَنْ</td>
      <td>ثَ ثِ ثُ بثْ</td>
    </tr>
    <tr>
      <td>جَنِجًا</td>
      <td>مَجِيْجًا</td>
      <td>الْمُجْنِ</td>
      <td>مِنَ</td>
      <td>جَجْنَ</td>
      <td>جَنِ</td>
      <td>جُوْ جَنْ</td>
      <td>جَ جِ جُ بَجْ</td>
    </tr>
    <tr>
      <td>حَنِحًا</td>
      <td>مَحِيْحًا</td>
      <td>الْمُحْنِ</td>
      <td>مِنَ</td>
      <td>حَحْنَ</td>
      <td>حَنِ</td>
      <td>حُوْحَنْ</td>
      <td>حَ حِ حُ بَحْ</td>
    </tr>
    <tr>
      <td>خَنِخًا</td>
      <td>مَخِيْخًا</td>
      <td>الْمُخْنِ</td>
      <td>مِنَ</td>
      <td>خَخْنَ</td>
      <td>خَنِ</td>
      <td>خُوْخًا</td>
      <td>خَ خِ خُ بَخْ</td>
    </tr>
    <tr>
      <td>دَنِدًا</td>
      <td>مَدِيْدًا</td>
      <td>الْمُدْنِ</td>
      <td>مِنَ</td>
      <td>دَدْنَ</td>
      <td>دَنِ</td>
      <td>دُوْدَنْ</td>
      <td>دَ دِ دُ بَدْ</td>
    </tr>
    <tr>
      <td>ذَنِذًا</td>
      <td>مَذِيْذًا</td>
      <td>الْمُذْنِ</td>
      <td>مِنَ</td>
      <td>ذَذْنَ</td>
      <td>ذَنِ</td>
      <td>ذُوْذَنْ</td>
      <td>ذَ ذِ ذُ بَذْ</td>
    </tr>
    <tr>
      <td>رَّنِرًا</td>
      <td>مَرِيْرًا</td>
      <td>الْمُرْنِ</td>
      <td>مِنَ</td>
      <td>رَرْنَ</td>
      <td>رَّنِ</td>
      <td>رُوْرَنْ</td>
      <td>رَ رِ رُ بَرْ</td>
    </tr>
    <tr>
      <td>زَنِزًا</td>
      <td>مَزِيْزًا</td>
      <td>الْمُزْنِ</td>
      <td>مِنَ</td>
      <td>زَزْنَ</td>
      <td>زَنِ</td>
      <td>زُوْزَنْ</td>
      <td>زَ زِ زُ بَزْ</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>مِنَ</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </table>
  <div dir="rtl">
    <span class="arabic" dir="rtl" lang="ar">
    </span>
  </div>
</div>
@endsection

@section('body')
<script>@include('tahsin.script')</script>
@endsection
